### ISSUE TITLE
Add Click-to-Publish Goal Feature for Protobuf Messages in 3D Panel

### ISSUE THREAD

**Issue by DYwasd** [foxglove/community#1019]
### Discussed in https://github.com/orgs/foxglove/discussions/1014

<div type='discussions-op-text'>

<sup>Originally posted by **DYwasd** July 12, 2024</sup>
#### Background and Motivation
Currently, the 3D panel in Foxglove Studio supports the click-to-publish goal feature for ROS message formats. This feature greatly enhances usability by allowing users to easily set goals within the 3D environment. However, this functionality is not available for Protobuf message formats. Adding this feature would provide a consistent user experience and extend the usability of the 3D panel for those using Protobuf messages.

#### Feature Description
- Enable the click-to-publish goal feature for Protobuf message formats in the 3D panel.
- The implementation should mirror the existing functionality available for ROS message formats.
- Ensure that users can configure and customize the goals for Protobuf messages just as they can for ROS messages.

#### Additional Information
Providing this feature will enhance the flexibility and functionality of the 3D panel, making Foxglove Studio more versatile and user-friendly for a wider range of users.

Thank you for considering this feature request.
</div>

**Comment by banisadr** [comment]
Thanks @DYwasd, we've noted this as a feature request in our tracking system.

**Comment by DYwasd** [comment]
You're welcome! @banisadr ，If you have any more details or specific requirements for the feature, please feel free to share them with us. We'll keep you updated on the progress. Thank you for your input!
