### ISSUE TITLE
Foxgolve Studio Receive time vs header.stamp

### ISSUE THREAD

**Issue by tyuownu** [foxglove/community#694]
### Discussed in https://github.com/orgs/foxglove/discussions/693

<div type='discussions-op-text'>

<sup>Originally posted by **tyuownu** April 14, 2023</sup>
Hi Guys, When I used Foxglove Studio for ROS2 program develop, I'm confused with the timestamp of foxglove studio.
Below image, the `orange` line represent `Receive time`, and the `blue` line represent `header.stamp`.
![header_stamp](https://user-images.githubusercontent.com/6268323/231968682-882d57aa-1115-440b-ba8c-ffb26e66a2ec.png)
![foxglove_receive_time](https://user-images.githubusercontent.com/6268323/231968718-df8af24b-d0d5-4a77-b88f-e69d32e2d938.png)

1. Why there have three different time in this images?
2. I know there is some wrong with my data, but why the `orange` line are my header time not the `blue` line?

Otherwise, the data in `orange` and `blue` line are same except the PEAKs in the image.

Thanks</div>

**Comment by defunctzombie** [comment]
Closing this in favor of the discussion: https://github.com/orgs/foxglove/discussions/693
