### ISSUE TITLE
Foxglove running in Docker on remote machine with X11 forwarding

### ISSUE THREAD

**Issue by gurucharansrinivas** [foxglove/community#781]
### Discussed in https://github.com/orgs/foxglove/discussions/780

<div type='discussions-op-text'>

<sup>Originally posted by **gurucharansrinivas** July 19, 2023</sup>
![image](https://github.com/foxglove/community/assets/16922384/0cdc373a-30aa-44a9-a5b6-2d4d2ef5b99c)
I encounter the above issue while launching Foxglove in a container running on the remote machine(ubuntu) with X11 forwarding. 
Apps like Xeyes work without any issues. Could someone provide a solution here?</div>

**Comment by defunctzombie** [comment]
Closing in favor of the discussion
