### ISSUE TITLE
Unexpected behaviour of "Sync annotations" feature

### ISSUE THREAD

**Issue by jtbandes** [foxglove/community#908]
### Discussed in https://github.com/orgs/foxglove/discussions/902

<div type='discussions-op-text'>

<sup>Originally posted by **DerMasri** January  3, 2024</sup>
@
[sync_problem.zip](https://github.com/foxglove/community/files/13819527/sync_problem.zip)

Hi together =)

I have a question regarding the "Sync annotations" feature. I have generated a test mcap file.
The annotations & image have exactly the same timestamp. Also the timestamps of the mcap entry are identical.

Turning the feature on, gives me "Waiting for synchronized annotations…" in the image panel all the time.
What am I doing wrong? Or is the feature currently not working properly?

Thanks a lot =)</div>

**Comment by snosenzo** [comment]
@DerMasri Should be fixed in #7328 and will be out in the next release, but let do reopen if you see it again
